Add test cases for SET with quoted string
6X_stable has a bug with single quote `'` in the string GUC value, which
will cause a incorrect quoted string gets dispatched to QEs. e.g.:

> SET search_path = "'";
ERROR:  unterminated quoted string at or near "'"

"SET search_path = '" will be dispatched instead of the correct one
"SET search_path = ''''"

Luckily the bug has been fixed on master by 320af40b31f5.
This commit adds test cases to prepare to be backported to 6X with
the original fix together.