Allow using a merge join for a dummy FULL JOIN ON TRUE.
Like in the 'join' regression test:

postgres=# select * from int4_tbl a full join int4_tbl b on true;
ERROR:  Query requires a feature that has been disabled by a configuration setting.
DETAIL:  Could not devise a query plan for the given query.
HINT:  Current settings:  optimizer=off