Fix XML whitespace option parsing
At some point in the past it seems the keyword list was merged from
upstream 8.4 without merging the actual code, and instead keywords
which weren't yet supported where commented out. The XML whitespace
keywords for STRIP WHITESPACE and PRESERVE WHITESPACE were however
not uncommented when XML support was merged, resulting in the below
error when trying to restore the XML views in ICW back after a dump:

db=# SELECT XMLPARSE(CONTENT '<abc>x</abc>'::text PRESERVE WHITESPACE) AS "xmlparse";
ERROR:  syntax error at or near "WHITESPACE"
LINE 1: ...CT XMLPARSE(CONTENT '<abc>x</abc>'::text PRESERVE WHITESPACE...
                                                             ^
Put the keywords back, and also remove commented out keywords which
we dont support but will get when merging 8.4 to reduce the diff with
upstream. Also add a testcase for XML whitespace syntax parsing.