Fully qualify GPOS type names in macros and convert the limits into enums.
GPOS deliberately clobbers at least 4 of the standard integral limit macros
(using #undef) such as ULONG_MAX, ULLONG_MAX etc. This causes several problems:

   *Including Xerces C++ headers after GPOS headers would lead to a compilation failure:

    /usr/local/include/xercesc/validators/common/Grammar.hpp:68: error: 'INT' was not declared in this scope
    /usr/local/include/xercesc/validators/common/Grammar.hpp:68: error: 'ULONG' was not declared in this scope
    /usr/local/include/xercesc/validators/common/Grammar.hpp:68: error: a function call cannot appear in a constant-expression
    /usr/local/include/xercesc/validators/common/Grammar.hpp:69: error: 'INT' was not declared in this scope
    /usr/local/include/xercesc/validators/common/Grammar.hpp:69: error: 'ULONG' was not declared in this scope
    /usr/local/include/xercesc/validators/common/Grammar.hpp:69: error: a function call cannot appear in a constant-expression

   *The worse thing that can happen than a compilation failure is a successful
    compilation: we only get surprised at runtime. Libraries we use (e.g. Xerces
    C++) may use these standard macros in their headers. The libraries we link to
    will be compiled with the actual standard values of those macros. By overriding
    INT_MAX and ULONG_MAX, for example, ORCA may assume one "orca value" of
    UINT_MAX (which in many implementations is defined in terms in INT_MAX) from
    Xerces, but will link to Xerces library code that uses a different value of
    UINT_MAX.

   *Longer feedback loop: this sort of falls into the bucket of "bad practice",
    which means that you don't necessarily get a failure on the platform and
    toolchain that you develop (say, Clang on Darwin), but will fail when you run a
    "more serious" test (say GCC on Linux).

   *This also impedes the best-practice that header files are conventionally
    re-orderable (with judicious exceptions)

Even if we define the macros lexically within the namespace curly
braces, they are still in the realm of the preprocessor and hence we
need to take extreme caution when it comes to ensuring that they are not
ambiguous.

This commit fully namespace-qualify the integral type names from GPOS to ensure
they are not ambiguous in macro expansions. Also it converts the limits for
these types into enums.

Fixes issue greenplum-db/gporca#358