Fix the project list of SplitUpdate
Take the case below:

```
CREATE TABLE foo (
    a_dist int,
    b int,
    c_part int
)
WITH (appendonly=false) DISTRIBUTED BY (a_dist) PARTITION BY RANGE(c_part)
          (
          PARTITION p20190305 START (1) END (2) WITH (tablename='foo_1_prt_p20190305', appendonly=false    )
          );
;

insert into foo(a_dist, c_part)  values (12,1);

update foo set b=c_part;
```
For the UPDATE statement above, the CPhysicalSplitUpdate will receive delete and insert columns as below:
InsertColIdx: 0 2 2
DeleteColIdx: 0 1 2

Currently we use InsertColIdx as our project list. Doing so gave us an error while running the
update statement.

```
ERROR: no partition for partitioning key (seg1 127.0.0.1:25433 pid=41342)
```

In GPDB, the DML node (specifically, the ExecDelete codepath) will use the project list of its child (SplitUpdate) to
determine which partition it should delete from. We saw that in ExecDelete, the
tuple values were incorrect, and the wrong value caused the logic to think that
the value to be deleted did not belong in the partition.

Instead, the SplitUpdate node should project the columns of the table being
updated, so DeleteColIdx should be projected. The projected columns only seem
to be used for partition selection; they're not needed/used for the insertion
part of SplitUpdate operations.

Co-authored-by: Sambitesh Dash <sdash@pivotal.io>
Co-authored-by: Chris Hajas <chajas@pivotal.io>