Update gpshrink: fix reference before assignment (#636)
Traceback (most recent call last):
  File "/usr/local/gpdb/bin/gpshrink", line 1509, in <module>
    main(options, args, parser)
  File "/usr/local/gpdb/bin/gpshrink", line 1477, in main
    if not (gpshrink_db_status is None):
UnboundLocalError: local variable 'gpshrink_db_status' referenced before assignment