Similar to optimizer plan, make executor code to free the bitmap for planner plan.
Similar to the optimizer, in planner with this
change`BitmapIndexScanState` is responsible for freeing the bitmaps
during `ExecEnd` or `ExecRescan`. The parent node doesn't need to worry
about freeing the bitmaps.

This also fix the following error for planner plan(bitmapscan_ao.sql).
```
select count(1) from bmcrash b1, bmcrash b2 where b1.bitmap_col =
b2.bitmap_col or b1.bitmap_col = '999' and b1.btree_col1 = 'abcdefg999';
ERROR:  non hash bitmap (nbtree.c:572)  (seg1 slice2 127.0.0.1:25433
pid=83873)
```