Revert "Fix logfile_getname()"
CI red with unit test failure:

```
[ RUN         ] test__open_alert_log_file__NonGucOpen
[          OK ] test__open_alert_log_file__NonGucOpen
[ RUN         ] test__open_alert_log_file__NonMaster
[          OK ] test__open_alert_log_file__NonMaster
[ RUN         ] test__open_alert_log_file__OpenAlertLog
                "gpperfmon/logs/alert_log.1.log" != "gpperfmon/logs/alert_log.12345"
                ERROR: Check of parameter filename, function fopen failed
Expected parameter declared at syslogger_test.c:69
                ERROR: syslogger_test.c:19 Failure!
[      FAILED ] test__open_alert_log_file__OpenAlertLog
[=============] 3 tests ran
[ PASSED      ] 2 tests
[ FAILED      ] 1 tests, listed below
[ FAILED      ] test__open_alert_log_file__OpenAlertLog
```

This reverts commit ffb2cf087c45f58da1b0e3f545991edb25740537.