concourse pipeline: unblock parsing by pyyaml
If the reusable anchors are declared at the end, some yaml parsers may
have trouble reading the file. In this case, pyyaml was throwing:

```
yaml.composer.ComposerError: found undefined alias 'ccp_create_params'
  in "<string>", line 702, column 11:
          <<: *ccp_create_params
              ^
```