Fix error position in the errors reported from gp_dump_query_oids()
If an invalid query is passed to gp_dump_query_oids(), the error position
would incorrectly point at the location in the original query, containing
the call to gp_dump_query_oids() call, rather than the query passed as
argument to it. For example:

regression=# select gp_dump_query_oids('select * from invalid');
ERROR:  relation "invalid" does not exist
LINE 1: select gp_dump_query_oids('select * from invalid');
                      ^

To fix, set up error context information correctly before parsing the
query.