Add assert that number of sort columns is 1 always for range in window functions.
Coverity complains that the function `cmp_deformed_tuple` access the
datum from expression eval as an array. But we don't have that use case due to the
following error. For e.g., the parser will complain that it can't have
more than 1 columns for sorting when we use range in window function as shown below.

```
select depname, empno, salary, LAST_VALUE(salary)
error.
over (partition by depname order by empno, salary range
between 5000 preceding and 3900 preceding) as
highest_salary from empsalary;
ERROR:  only one ORDER BY column may be specified when RANGE is used in
a window specification
```