walrep: Fix maybe-unitialized warnings in test_receive_and_verify()
Prior to this commit, the below warnings were occurring on GCC 6.2.0.

The warnings seem valid but unlikely, so we just NULL initialize
logStreamStart, which would most likely still land in the correct error
case.

gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Werror=uninitialized -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address  -fpic -I. -I. -I../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o gplibpq.o gplibpq.c
In file included from ../../../src/include/postgres.h:53:0,
                 from gplibpq.c:7:
gplibpq.c: In function 'test_receive_and_verify':
../../../src/include/utils/elog.h:311:3: error: 'logStreamStart.xrecoff' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   elog_finish(elevel, __VA_ARGS__); \
   ^~~~~~~~~~~
gplibpq.c:140:15: note: 'logStreamStart.xrecoff' was declared here
    XLogRecPtr logStreamStart;
               ^~~~~~~~~~~~~~
In file included from ../../../src/include/postgres.h:53:0,
                 from gplibpq.c:7:
../../../src/include/utils/elog.h:311:3: error: 'logStreamStart.xlogid' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   elog_finish(elevel, __VA_ARGS__); \
   ^~~~~~~~~~~
gplibpq.c:140:15: note: 'logStreamStart.xlogid' was declared here
    XLogRecPtr logStreamStart;
               ^~~~~~~~~~~~~~

Signed-off-by: Amil Khanzada <akhanzada@pivotal.io>