ci: depends on more-itertools<8.1
The current version of more-itertools is 8.1.0 and will cause below
error:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UK2VKZ/more-itertools/setup.py", line 5, in <module>
        from more_itertools import __version__
      File "more_itertools/__init__.py", line 1, in <module>
        from .more import *  # noqa
      File "more_itertools/more.py", line 480
        yield from iterable
                 ^
    SyntaxError: invalid syntax

It used to work well with more-itertools 8.0.2, so we need to specify
that we need a version < 8.1

Also make sure that we call pip install with the proper dependence
requirements.