Revert "Explicitly call python3 in python scripts. (#11553)"
This reverts commit 1929fecc5b1ce0815bfb7419b37821b733be2c56.

The gppkg ci job fails since the commit.

Traceback (most recent call last):
        File "/usr/local/greenplum-db-devel/lib/python/gppylib/commands/base.py", line 276, in run
          self.cmd.run()
        File "/usr/local/greenplum-db-devel/lib/python/gppylib/operations/__init__.py", line 53, in run
          self.ret = self.execute()
        File "/usr/local/greenplum-db-devel/lib/python/gppylib/operations/package.py", line 1020, in execute
          if not CheckRemoteDir(GPPKG_ARCHIVE_PATH, self.host).run():
        File "/usr/local/greenplum-db-devel/lib/python/gppylib/operations/__init__.py", line 53, in run
          self.ret = self.execute()
        File "/usr/local/greenplum-db-devel/lib/python/gppylib/operations/unix.py", line 46, in execute
          return pickle.loads(cmd.get_results().stdout)
      _pickle.UnpicklingError: unpickling stack underflow

This failure seems to have nothing to do this commit. Let me revert it at first
to unblock code pushing, and then look further later.