Fix pgbench --tablespace option.
The CREATE TABLE commands constructed in pgbench had the DISTRIBUTED BY
and TABLESPACE options the wrong way 'round, so that you got a syntax
error. For example:

$ pgbench postgres -i --tablespace "pg_default"
creating tables...
ERROR:  syntax error at or near "tablespace"
LINE 1: ...22)) with (appendonly=false) DISTRIBUTED BY (bid) tablespace...
                                                             ^
Put the clauses in right order.

We have no test coverage for this at the moment, but PostgreSQL v11 adds
a test for this (commit ed8a7c6fcf). I noticed this while looking at test
failures with the PostgreSQL v12 merge.

Reviewed-by: Ashwin Agrawal <aagrawal@pivotal.io>