Fix Some commands forgot to mark meta track.
Issue https://github.com/cloudberrydb/cloudberrydb/issues/504

It will make unstable cases failed as:
ERROR:  duplicate key value violates unique constraint
"pg_statlastop_classid_objid_staactionname_index"

Call MetaTrackDropObject in functions:
  RemoveSchemaById
  RemovePublicationById
  RemovePolicyById

Authored-by: Zhang Mingli avamingli@gmail.com
(cherry picked from commit 472db7698467d41348eb15c6b76e7a8aabf5b909)