Allow standard, thread-safe, C99 functions.
This includes:

* all trigonometric functions (sin(), cos(), ...)
* other standard math functions (sqrt(), floor(), abs(), ...)
* complex number functions (cround(), ccos(), csqrt(), ...)
* standard memory manipulation functions (memcpy(), memset(), memchr(), ...)
* standard string functions (strlen(), strchr(), strstr(), ...)

These are all thread-safe.

I left out (i.e. they are still banned) a few widely-available related
functions, which are however not in the C99 standard, like drem() or
strchrnul(). I wouldn't mind much allowing those too, but for now I stuck
with C99, for the sake of principle.

The acute reason for doing this now is that I started to get compilation
errors on GPDB after I updated libc-dev package on my Debian system to
version 2.22-9:

In file included from /usr/include/features.h:361:0,
                 from /usr/include/stdio.h:27,
                 from ../../../../src/include/c.h:72,
                 from ../../../../src/include/postgres.h:47,
                 from CTranslatorScalarToDXL.cpp:17:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:1: error: ‘__DECL_SIMD_USE_OF_BANNED_API_exp’ does not name a type
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
 ^

Apparently the new glibc headers don't like it when standard library
functions are #defined to something invalid.