s3ext: fix compilation error on CentOS 7 with GCC 4.8.5 (#180)
s3ext fail to compile on CentOS 7,
/usr/include/libintl.h:39:14: error: expected unqualified-id before ‘const’
 extern char *gettext (const char *__msgid)

Root cause:
In greenplum-db-devel/include/postgresql/server/c.h
ENABLE_NLS macro controls gettext function definition.

#ifdef ENABLE_NLS
#ifndef __S3_COMMON_HEADERS_H__
#include <libintl.h>
#else
#include "s3utils.h"
#define gettext(x) (x)
#define dgettext(d,x) (x)
#define ngettext(s,p,n) ((n) == 1 ? (s) : (p))
#define dngettext(d,s,p,n) ((n) == 1 ? (s) : (p))
#endif

If c.h is included before libintl.h, and ENABLE_NLS is not defined,
gettext function definition in libintl.h be replaced.

libintl.h is also included by iomanip.h

Resolve:
Move iomanip.h to s3utils.cpp

Signed-off-by: Ning Wu <nwu@pivotal.io>