Mask out difference in exttab1 test output.
The shell on my laptop produces an error like:

ERROR:  external table ext_stderr1 command ended with error. sh: 1: ...

while the expected output is:

ERROR:  external table ext_stderr1 command ended with error. sh: ...

(Note the missing line number, "1: ").

Add a substitution pattern to the test case to mask that out. There was
already a similar pattern for shells that print "line 1:".