Include <signal.h> to fix compiler error on MacOS (#11135)
After commit aef9968059faf33e master build on macOS started to fail with
errors like this:

execute_pipe.c:197:6: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (kill(pid, 0) == 0) /* process exists */
            ^
1 error generated.

POSIX only guarantees that kill(2) be provided through <signal.h>. It
turns out we were relying on <unistd.h> to indirectly include <signal.h>
for us. But that's a GNU-ism.

This also showed up in Travis CI on greenplum-db/gpdb#11121
(https://travis-ci.org/github/greenplum-db/gpdb/builds/742342058) before
it got merged into master.

Co-authored-by: Shreedhar Hardikar <hardikar@cs.wisc.edu>
Co-authored-by: Jesse Zhang <sbjesse@gmail.com>