Add required headerfile for reconstructTupleValues()
Fixes compiler warning for implicit declaration due to missing
headerfile include:

  copy.c:4143:6: warning: implicit declaration of function
     'reconstructTupleValues' is invalid in C99
     [-Wimplicit-function-declaration]