Detach postmaster process from pg_ctl's session at server startup.
The PostgreSQL 9.2 merge added a setsid() call to postmaster.c,
to work around issues on killing the regression tests. But that
introduced problems of its own. If you started postmaster directly from the
command line, with something like "postgres -D datadir", it would fail with:

ERROR: setsid() failed: Operation not permitted (postmaster.c:1025)

Another symptom was that I was not able to kill the server with CTRL-C,
in the little bash script I use to launch the server. My bash script
simply launches all the servers with:

    #!/bin/bash
    postmaster -D data-seg0 &
    postmaster -D data-seg1 &
    postmaster -D data-seg2 &
    postmaster -D data-master

Commit message from the change on the 9.2 merge branch that
introduced the setsid() call:

commit ef0cb844c87d8b9769b98a20ca66ecda00620604
Author: Paul Guo <paulguo@gmail.com>
Date:   Fri Jul 27 18:11:31 2018 +0800

    Set up a new session group in postmaster.

    Without this patch, pressing ctrl+c to terminate regression tests
    could always cause master processes down if master is identical as client.

    This issue 100% happens after running into tests in greenplum_schedule.
    It is because the first test case instr_in_shmem_setup in
    greenplum_schedule restarts the cluster, however without this patch,
    when we press ctrl+c to terminate testing, SIGINT will
    be delivered to postmaster process also.

    This issue does not happen on gpdb master at this moment due to
    the existence of pmdaemonize() which was removed in PG 9.2, and
    since the logic on PG seems to be never changed since 9.2 it
    happens on PG master also.

    Not sure how PG upstream thinks about this, but I'm checking in
    this patch at first since this really affect development.

This was really a problem in PostgreSQL, too, but no one had noticed or
complained about it. After discussion on pgsql-hackers, it was fixed by
this upstream commit:

commit bb24439cefead34f195c78f400982f3834593df6
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Mon Jan 14 14:50:58 2019 +0200

    Detach postmaster process from pg_ctl's session at server startup.

    pg_ctl is supposed to daemonize the postmaster process, so that it's not
    affected by signals to the launching process group.  Before this patch, if
    you had a shell script that used "pg_ctl start", and you interrupted the
    shell script after postmaster had been launched, postmaster was also
    killed.  To fix, call setsid() after forking the postmaster process.

    Long time ago, we had a 'silent_mode' option, which daemonized the
    postmaster process by calling setsid(), but that was removed back in 2011
    (commit f7ea6beaf4).  We discussed bringing that back in some form, but
    pg_ctl is the documented way of launching postmaster to the background, so
    putting the setsid() call in pg_ctl itself seems appropriate.

    Just putting postmaster in a separate session would change the behavior
    when you interrupt "pg_ctl -w start", e.g. with CTRL-C, while it's waiting
    for postmaster to start.  The historical behavior has been that
    interrupting pg_ctl aborts the server launch, which is handy if the server
    is stuck in recovery, for example, and won't fully start up.  To keep that
    behavior, install a signal handler in pg_ctl, to explicitly kill
    postmaster, if pg_ctl is interrupted while it's waiting for the server to
    start up.  This isn't 100% watertight, there is a small window after
    forking the postmaster process, where the signal handler doesn't know the
    postmaster's PID yet, but seems good enough.

    Arguably this is a long-standing bug, but I refrained from back-batching,
    out of fear of breaking someone's scripts that depended on the old
    behavior.

    Reviewed by Tom Lane.  Report and original patch by Paul Guo, with
    feedback from Michael Paquier.

    Discussion: https://www.postgresql.org/message-id/CAEET0ZH5Bf7dhZB3mYy8zZQttJrdZg_0Wwaj0o1PuuBny1JkEw%40mail.gmail.com

This commit reverts the new setsid() call that was added during the 9.2
merge, and backports that upstream fix, instead.