Remove the unstable legacy tests.
[#127140493] This checkin will make ICG green in gpdb_pr pipeline.

- Separate the alter_table_ao as its own test group

- Separate bitmap_index as its own test group

- Make the utable and uview independent across tests

Both gp_numeric_agg and qp_misc_jiras are using uviews, which caused side-effect
across tests. This fix totally separate those two tests.

- Separate `partition_indexing` as its own group

Sometime, this test failed with under low resource:
ERROR:  Inserting with invalid TID (0,0) into relation id 220616 'mpp3033b_stringu1', relfilenode 221541, segment file #0, serial number 0