Trying to make parallel_retrieve_cursor/fault_inject stable. (#13141)
This patch is trying to make isolation2/parallel_retrieve_cursor/fault_inject
stable by replacing 'sleep' fault with 'suspend' fault.

Below is the regression.diffs file fetched from the PR pipeline.

```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /tmp/build/d62a0504/gpdb_src/src/test/isolation2/expected/parallel_retrieve_cursor/fault_inject.out /tmp/build/d62a0504/gpdb_src/src/test/isolation2/results/parallel_retrieve_cursor/fault_inject.out
--- /tmp/build/d62a0504/gpdb_src/src/test/isolation2/expected/parallel_retrieve_cursor/fault_inject.out	2022-02-24 16:18:00.128491568 +0000
+++ /tmp/build/d62a0504/gpdb_src/src/test/isolation2/results/parallel_retrieve_cursor/fault_inject.out	2022-02-24 16:18:00.940556278 +0000
@@ -684,6 +684,3256 @@
  READY
 (1 row)
 2R&: @pre_run 'set_endpoint_variable @ENDPOINT6': RETRIEVE ALL FROM ENDPOINT "@ENDPOINT6";  <waiting ...>
+FAILED:  Forked command is not blocking; got output: a
+-------
+ 5
+ 6
+ 9
+ ...
+ 9999
+ 10000
+(3247 rows)

 1U: SELECT state FROM gp_segment_endpoints() WHERE cursorname='c1';
  state
@@ -699,7 +3949,7 @@
 0R<:  <... completed>
 ERROR:  endpoint is not available because the parallel retrieve cursor was aborted (cdbendpointretrieve.c:LINE_NUM)
 2R<:  <... completed>
-ERROR:  endpoint is not available because the parallel retrieve cursor was aborted (cdbendpointretrieve.c:LINE_NUM)
+FAILED:  Execution failed

 1<:  <... completed>
 FAILED:  Execution failed
```