Re-enable upstream optimization to pull up simple UNION ALL subqueries.
There's no good reason to not do it anymore. It was disabled back in 2008,
when this test query was failing:

postgres=# create table tab as select generate_series(1,10) as a;
SELECT 10
postgres=# select * from tab where a in (select a from tab where a = 2 union all values (4));
ERROR:  Cannot append paths with incompatible distribution

But that's been fixed a long time ago, there's now code that adds Motions
as needed to the branches of an append relation, and there are test cases
for that in the 'union_gp' test. That query works fine now with the
optimization.

Some changes were required in examine_simple_variable(), because the code
that was added there for the 'gp_statistics_pullup_from_child_partition'
GUC assumed that all range table entries with 'inh==true' must be of
kind RTE_RELATION, but that's not true for the pulled up subqueries. Fix
that assumption.

Reviewed-by: Richard Guo <riguo@pivotal.io>