Fix quoting when resetting a GUC.
Strangely enough, this was causing this failure in the 'alter_table' test,
while working on the v12 merge:

create temp table foo (f1 text, f2 mytype, f3 text);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'f1' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  no pre-assigned OID for pg_namespace tuple "pg_temp_26" (namespace:0 keyOid1:0 keyOid2:0) (oid_dispatch.c:360)  (seg2 127.0.0.1:40002 pid=24218) (oid_dispatch.c:360)

An earlier ALTER TABLE ADD CONSTRAINT command left 'default_tablespace' in
the list of GUCs to be reset, but because default_tablespace was set to
an empty string, the restore command was just "SET default_tablespace = ",
which failed. The error was caught and suppressed, but it caused the next
command to fail.

NOTE: This isn't new with the v12 merge. But something changed with how
default_tablespace is set in this case. Possibly needs to be fixed in
backbranches too, though.